<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup Label="platform and framework environment">
        <LangVersion>14.0</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup Label="package metadata">
        <PackageId>akanse.$(AssemblyName)</PackageId>
        <Title>QuantitiesDotNet</Title>
        <Version>0.2.0</Version>
        <Authors>aka-nse</Authors>
        <Company></Company>
        <Description>.Net library for physical quantity handling</Description>
        <PackageTags>quantities,physics,measurements</PackageTags>
        <PackageProjectUrl>https://github.com/aka-nse/QuantitiesDotNet</PackageProjectUrl>
        <RepositoryUrl>https://github.com/aka-nse/QuantitiesDotNet</RepositoryUrl>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    </PropertyGroup>

    <PropertyGroup>
      <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../QuantitiesDotNet.Generators/QuantitiesDotNet.Generators.csproj">
            <OutputItemType>Analyzer</OutputItemType>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
      <None Include="../../LICENSE.txt" Pack="true" PackagePath="/" />
      <None Include="../../readme.md" Pack="true" PackagePath="/" />
      <None Include="../../resource/icon.png" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Collections.Immutable" Version="9.0.4" />
      <PackageReference Include="System.Memory" Version="4.6.3" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Quantities/QHalfway_NoNamedDimensions.tt">
        <Generator>TextTemplatingFileGenerator</Generator>
        <LastGenOutput>QHalfway_NoNamedDimensions.g.cs</LastGenOutput>
      </None>
        <None Include="Quantities/QHalfway_NoNamedDimensions.g.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>QHalfway_NoNamedDimensions.tt</DependentUpon>
        </None>
    </ItemGroup>

    <ItemGroup>
      <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="../QuantitiesDotNet.Shared/PlatformCapabilities.cs" Link="PlatformCapabilities.cs" />
    </ItemGroup>
    
    <ItemGroup>
      <Compile Update="Quantities/QHalfway_NoNamedDimensions.g.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>QHalfway_NoNamedDimensions.tt</DependentUpon>
      </Compile>
    </ItemGroup>
</Project>
