<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0</TargetFrameworks>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <PackageId>akanse.$(AssemblyName)</PackageId>
        <Title>QuantitiesDotNet</Title>
        <Description>.Net library for physical quantity handling</Description>
        <AssemblyVersion>0.2.0.0</AssemblyVersion>
        <FileVersion>$(AssemblyVersion)</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\QuantitiesDotNet.Generators\QuantitiesDotNet.Generators.csproj">
            <OutputItemType>Analyzer</OutputItemType>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\QuantitiesDotNet.Shared\PlatformCapabilities.cs" Link="PlatformCapabilities.cs" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\..\LICENSE">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
      <None Include="..\..\readme.md">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
      <None Include="..\..\resource\icon.png">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Collections.Immutable" Version="9.0.4" />
      <PackageReference Include="System.Memory" Version="4.6.3" />
    </ItemGroup>

    <ItemGroup>
      <None Update="QHalfway_NoNamedDimensions.tt">
        <Generator>TextTemplatingFileGenerator</Generator>
        <LastGenOutput>QHalfway_NoNamedDimensions.g.cs</LastGenOutput>
      </None>
        <None Include="QHalfway_NoNamedDimensions.g.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>QHalfway_NoNamedDimensions.tt</DependentUpon>
        </None>
    </ItemGroup>

    <ItemGroup>
      <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="QHalfway_NoNamedDimensions.g.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>QHalfway_NoNamedDimensions.tt</DependentUpon>
      </Compile>
    </ItemGroup>
</Project>
