namespace QuantitiesDotNet;
using Generic;


public partial class QuantityTest
{
    public static partial TheoryData<object> TypeArgumentProvider_NonGeneric()
        => [
            new QAcceleration(1.0),
            new QAngle(1.0),
            new QAngularAcceleration(1.0),
            new QAngularVelocity(1.0),
            new QArea(1.0),
            new QCatalyticActivity(1.0),
            new QDensity(1.0),
            new QDimensionless(1.0),
            new QElectricCapacity(1.0),
            new QElectricCharge(1.0),
            new QElectricConductance(1.0),
            new QElectricConductivity(1.0),
            new QElectricCurrent(1.0),
            new QElectricFieldStrength(1.0),
            new QElectricFluxDensity(1.0),
            new QElectricIndactance(1.0),
            new QElectricResistance(1.0),
            new QElectricVoltage(1.0),
            new QEnergy(1.0),
            new QForce(1.0),
            new QFrequency(1.0),
            new QHeatCapacity(1.0),
            new QLength(1.0),
            new QLuminance(1.0),
            new QLuminousFlux(1.0),
            new QLuminousIntensity(1.0),
            new QMagneticFieldStrength(1.0),
            new QMagneticFlux(1.0),
            new QMagneticFluxDensity(1.0),
            new QMass(1.0),
            new QMassFlowRate(1.0),
            new QMomentum(1.0),
            new QPower(1.0),
            new QPressure(1.0),
            new QSolidAngle(1.0),
            new QSpatialFrequency(1.0),
            new QSpecificHeatCapacity(1.0),
            new QSpeed(1.0),
            new QSubstanceAmount(1.0),
            new QTemperature(1.0),
            new QTime(1.0),
            new QTorque(1.0),
            new QVolume(1.0),
        ];
        
    public static partial TheoryData<object> TypeArgumentProvider_Generic()
        => [
            new QAcceleration<decimal>(1.0m),
            new QAngle<decimal>(1.0m),
            new QAngularAcceleration<decimal>(1.0m),
            new QAngularVelocity<decimal>(1.0m),
            new QArea<decimal>(1.0m),
            new QCatalyticActivity<decimal>(1.0m),
            new QDensity<decimal>(1.0m),
            new QDimensionless<decimal>(1.0m),
            new QElectricCapacity<decimal>(1.0m),
            new QElectricCharge<decimal>(1.0m),
            new QElectricConductance<decimal>(1.0m),
            new QElectricConductivity<decimal>(1.0m),
            new QElectricCurrent<decimal>(1.0m),
            new QElectricFieldStrength<decimal>(1.0m),
            new QElectricFluxDensity<decimal>(1.0m),
            new QElectricIndactance<decimal>(1.0m),
            new QElectricResistance<decimal>(1.0m),
            new QElectricVoltage<decimal>(1.0m),
            new QEnergy<decimal>(1.0m),
            new QForce<decimal>(1.0m),
            new QFrequency<decimal>(1.0m),
            new QHeatCapacity<decimal>(1.0m),
            new QLength<decimal>(1.0m),
            new QLuminance<decimal>(1.0m),
            new QLuminousFlux<decimal>(1.0m),
            new QLuminousIntensity<decimal>(1.0m),
            new QMagneticFieldStrength<decimal>(1.0m),
            new QMagneticFlux<decimal>(1.0m),
            new QMagneticFluxDensity<decimal>(1.0m),
            new QMass<decimal>(1.0m),
            new QMassFlowRate<decimal>(1.0m),
            new QMomentum<decimal>(1.0m),
            new QPower<decimal>(1.0m),
            new QPressure<decimal>(1.0m),
            new QSolidAngle<decimal>(1.0m),
            new QSpatialFrequency<decimal>(1.0m),
            new QSpecificHeatCapacity<decimal>(1.0m),
            new QSpeed<decimal>(1.0m),
            new QSubstanceAmount<decimal>(1.0m),
            new QTemperature<decimal>(1.0m),
            new QTime<decimal>(1.0m),
            new QTorque<decimal>(1.0m),
            new QVolume<decimal>(1.0m),
        ];
}
